### ISSUE TITLE
Couldn't get extension to work in Firefox 73.0.1 on macOS

### ISSUE THREAD

**Issue by brettcannon** [Folyd/rust-search-extension#17]
There was no obvious way to trigger that a search term in the address bar should be sent through e.g. docs.rs or crates.io.

**Comment by Folyd** [comment]
Hey, could you please give more details here? What version are you using? Any screenshots? Thanks.

**Comment by brettcannon** [comment]
My first question is how do you expect the extension to be triggered? 😉 I actually couldn't find any documentation that specifically stated what the expected action was supposed to be to make the search bar switch to the extension.

**Comment by Folyd** [comment]
Thanks for feedback. You can input the keyword `rs` in the address, then press `Space`, the extension will be activated automatically.  Let me know if you have any other problems. :)

**Comment by g-plane** [comment]
This should be documented at readme or the website. I'm new to this extension and I'm also a Firefox user. I don't know how to open search box at the beginning, too.

**Comment by Folyd** [comment]
@g-plane It's true. Well, I did document this on the README and website. Maybe that not in an obvious way?  Anyway, thank your guys. 😃

**Comment by brettcannon** [comment]
> I did document this on the README and website. Maybe that not in an obvious way?

Ah, now I see it! What probably happened was my brain read that first line as "this text is the sales pitch, which I already bought into, so stop reading". The other thing is the animated GIF does _something_ to make the search bar say "Rust Search Extension" and I still don't know how to make that happen.

Either way, it's working as intended! Sorry about the noise.
