### ISSUE TITLE
Any plan to support Microsoft Edge?

### ISSUE THREAD

**Issue by zombie110year** [Folyd/rust-search-extension#25]
Chrome Store 在中国大陆无法访问。

**Comment by Folyd** [comment]
Of course, Microsoft Edge is in our support plan. Maybe in version 0.9 or version 1.0. Please stay tuned!

**Comment by Folyd** [comment]
Hey @zombie110year . Rust Search Extension is available on Microsoft Edge, welcome to give it a try! 🎉 
https://microsoftedge.microsoft.com/addons/detail/ebibclchdmagkhopidkjckjkbhghfehh
