### ISSUE TITLE
docs.rs should always be near top for perfect matches

### ISSUE THREAD

**Issue by vadixidav** [Folyd/rust-search-extension#26]
When I type in `log` I just see methods like f32::log, f64::log2, etc. Since `log` is a crate name, it should at least appear on the search list.

**Comment by vadixidav** [comment]
I will say that I have learned about the `fn ...` and `!!cratename` commands, which is proving to be more useful. This is a good solution for me in the interim.

**Comment by Folyd** [comment]
Hi @vadixidav , the default search priority is: **std docs** > **attributes** > **crates**. To search exclusively, you can prefix `#` for attributes searching, prefix `!` or `!!` for crates searching(crates.io and docs.rs seperately).
