### ISSUE TITLE
"rs<space>dashmap" gives HashMap documentation rathern than DashMap

### ISSUE THREAD

**Issue by rich-murphey** [Folyd/rust-search-extension#27]
First off, kudos for this extension. I'm using hourly pretty much anytime I'm coding these days.  Thanks so much for writing it!

this seems weird. 
upon entering "rs<space>dashmap" the dropdown shows 
"crate: dashmap v3.7.0...."
but pressing enter goes to:
https://doc.rust-lang.org/std/collections/struct.HashMap.html

**Comment by Folyd** [comment]
Hi @rich-murphey. Glad you like it and thankful for the feedback.

The std docs search is based on the **Levenshtein distance algorithm**, which means the search result is approximately matched to the keyword the user input. Hence is why when you search **dashmap**, the dropdown shows **hashmap**. 

Another caveat is we only support search std docs right now. Searching docs of the external crate is in our support plan. Please stay tuned!

Related issue: #20

**Comment by rich-murphey** [comment]
Thanks for the clarification.

I looked closer at this, and it's actually a firefox issue.
Pressing return does not got to the first, **highlghted** item on the dropdown, which is  confusing.  Return selects the second item. 

Using the mouse to click on the first item on the drop down goes to that item.
Sorry for the false alarm.

**Comment by Folyd** [comment]
@rich-murphey Yes, this is a Firefox bug. See #14
