### ISSUE TITLE
Where is Firefox AMO?

### ISSUE THREAD

**Issue by ncaq** [Folyd/rust-search-extension#3]
I want use this addon on Firefox.
However, I do not found this addon on AMO.
Will do you release for Firefox?

When you is busy, I push AMO instead.

**Comment by Folyd** [comment]
Hi @ncaq , unfortunately, the extension is not available in Firefox AMO right now, I have a plan to publish to AMO, please do not publish it in your name. 

You can install to Firefox manually before the AMO version is available. If you don't know how to, you can Google it. It's pretty easy. Thanks. 😄

**Comment by Folyd** [comment]
> I want use this addon on Firefox.
> However, I do not found this addon on AMO.
> Will do you release for Firefox?
> 
> When you is busy, I push AMO instead.

Hi @ncaq , Firefox version is available on AMO, welcome to give it a try! 😄
