### ISSUE TITLE
Opening in new tab should be done with the Alt modifier

### ISSUE THREAD

**Issue by chris-morgan** [Folyd/rust-search-extension#5]
In both Firefox and Chrome, Enter opens the address bar thing in the current tab, and Alt+Enter in a new tab. The “Open search result in…” preference should be removed and replaced with this standard mechanism.

I’m using Firefox.

**Comment by Folyd** [comment]
Thanks for the kind suggestion. It seems like this doesn't work on the extension when you using omnibox API. When you trigger the keyword `rs` to search rust doc, Alt + Enter to open a new tab is an incapable feature anymore.

**Comment by Folyd** [comment]
@chris-morgan Now the feature open in the new tab with ALT + Enter is available since version 0.8. Welcome to give it a try and let me know if you have any further questions. Thanks again. 😃
