### ISSUE TITLE
Path to docs isn’t clever enough

### ISSUE THREAD

**Issue by chris-morgan** [Folyd/rust-search-extension#8]
When I run `rustup doc --path`, I get this output:

```
C:\Users\me\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\share\doc\rust\html\index.html
```

But if I enter that verbatim, it gets it very wrong. Looks like what it needs is more like this:

```
file:///C:/Users/me/.rustup/toolchains/nightly-x86_64-pc-windows-msvc/share/doc/rust/html/
```

The extension should suggest that I run `rustup doc --path` (or run it itself, if it can), and figure out the right value from whatever it gives, and just generally be cleverer.

Firefox, Windows.

**Comment by Folyd** [comment]
Yeah, you're right. I have submitted some new commits to make local doc path detection more clever! Please stay tuned, thanks!
