### ISSUE TITLE
Unable to jump to correct page on offline mode

### ISSUE THREAD

**Issue by chirsz-ever** [Folyd/rust-search-extension#9]
I fill the "Input the local std doc path" box with `file:///home/chirsz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust/html/` which is my rust doc folder and I can visit it with broswer directly. When I type `rs Result` in URL bar and select the second option, it go to `https://doc.rust-lang.org/stable/std/?search=file%3A%2F%2F%2Fhome%2Fchirsz%2F.rustup%2Ftoolchains%2Fstable-x86_64-unknown-linux-gnu%2Fshare%2Fdoc%2Frust%2Fhtmlstd%2Fresult%2Findex.html` instead of `file:///home/chirsz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust/htmlstd/result/index.html` which I really want.
Is it a bug? Or I did something incorrect?

**Comment by Folyd** [comment]
@chirsz-ever Thanks for report. This is bug will be fixed in the next version.

**Comment by Folyd** [comment]
@chirsz-ever A new version was released, and this got fixed!
